package fr.mc2d.gamelauncher.saver;

import fr.mc2d.gamelauncher.util.logger.Logger;

import java.io.BufferedWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

public class Saver {

    private final Path file;

    private final Properties properties;

    public Saver(Path file) {
        this.file = file;
        this.properties = new Properties();

        if (Files.exists(this.file)) {
            this.load();
        } else {
            try {
                Files.createDirectories(this.file.getParent());
                Files.createFile(this.file);
            } catch (Throwable e) {
                Logger.LOGGER.err("Can't make the properties file");
            }
        }
    }

    public void set(String key, String value) {
        this.properties.setProperty(key, value);
        this.save();
    }

    public String get(String key) {
        return this.properties.getProperty(key);
    }

    public String get(String key, String def) {
        String value = this.properties.getProperty(key);
        return value == null ? def : value;
    }

    public void save() {
        try {
            BufferedWriter writer = Files.newBufferedWriter(this.file);
            this.properties.store(writer, "Generated by the MC2D's Saver");
            writer.close();
        } catch (Throwable t) {
            Logger.LOGGER.err("Can't save the properties file");
        }
    }

    public void load() {
        try {
            this.properties.load(Files.newInputStream(this.file));
        } catch (Throwable t) {
            Logger.LOGGER.err("Can't load the properties file", t);
        }
    }

    public void remove(String key) {
        this.properties.remove(key);
        this.save();
    }
}
